### ISSUE TITLE
Bold fonts on Firefox are rendered incorrectly

### ISSUE THREAD

**Issue by Tenchi2xh** [tetrio/issues#452]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

While making Tetrio Stats I noticed that screenshots from Firefox users looked ugly and at first didn't notice why but then I did: every piece of text using HUN that's supposed to be bold was awfully skinny and the letters spaced out

Here is a comparison from the login screen on TETR.IO:

![](https://user-images.githubusercontent.com/4116708/88537483-f1e9b900-d00d-11ea-8248-f225eb845665.png)

![](https://cdn.discordapp.com/attachments/673303546564968566/737254906003718245/unknown.png)
![](https://cdn.discordapp.com/attachments/673303546564968566/737254944196788344/unknown.png)

(top of each example is Chrome, bottom is Firefox)

I have found a way to "fix" this by setting an outline around the text only on Firefox using this trick:

```css
/* styles inside this are only applied on FF */
@supports (-moz-appearance:none) {
    label b, .intro-header b, .badge::after, .tr, table th /* etc ... every single style that uses bold */ {
        -webkit-text-stroke: 0.02em;
        letter-spacing: -0.02em;
    }
}
```

(This could also be remedied I think by properly having a HUN font pre-calculated for bold weights)
